import Image from "next/image";
import Head from "next/head";
import magnifyingGlass from "../components/analytics.png";
import report from "../components/report.png";
import goal from "../components/goal.png";
import logo from "../components/logo-moneydna-208-59.png";
import styles from "../styles/LandingPage.module.css";

export default function LandingPage() {
  let reviewGif =
    "https://www.shopperapproved.com/seal/35353/default-sa-seal.gif";

  return (
    <div style={{ padding: "0" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.root}>
        <div className={styles.header}>
          <Image src={logo} alt="MoneyDNA logo" />
        </div>
        <hr className={styles.hr} />
        <div style={{ flexGrow: 1 }}>
          <div className={styles.body}>
            <h3>
              Knowing your financial personality type makes you better at
              managing money.
            </h3>
            <p>
              100% free. Begin eliminating stress and reaching your financial
              goals today!
            </p>
            <button
              type="button"
              onClick={(e) => {
                e.preventDefault();
                window.open("https://themoneydnaquiz.com/dna515f/", "_blank");
              }}
            >
              Take Quiz
            </button>
          </div>

          <div className={styles.icons}>
            <div className={styles.icon__and__text}>
              <div className={styles.icon__images}>
                <Image
                  src={magnifyingGlass}
                  alt="magnifying glass over graph"
                  className={styles.icon__images}
                  height="400rem"
                  width="400rem"
                />
              </div>
              <p>
                Analytical model built with hundreds of permutations to
                determine your financial personality.
              </p>
            </div>
            <div className={styles.icon__and__text}>
              <div className={styles.icon__report}>
                <Image
                  src={report}
                  alt="financial report"
                  height="150rem"
                  width="150rem"
                />
              </div>
              <p style={{ marginLeft: "25px" }}>
                Get a unique report built just for you.
              </p>
            </div>

            <div className={styles.icon__and__text}>
              <div className={styles.icon__images}>
                <Image
                  src={goal}
                  alt="bullseye"
                  height="400rem"
                  width="400rem"
                />
              </div>
              <p>
                Learn how your beliefs could be affecting your budget and
                holding you back from reaching your financial goals.
              </p>
            </div>
          </div>
        </div>

        <div className={styles.footer}>
          <div className={styles.review__container}>
            <img
              onClick={(e) => {
                e.preventDefault();
                window.open(
                  "https://www.shopperapproved.com/reviews/moneydna.com",
                  "_blank"
                );
              }}
              src={reviewGif}
              alt="Customer Reviews"
            />
          </div>
          <p style={{ marginBottom: "-0.5rem" }}>
            <span
              style={{ cursor: "pointer" }}
              onClick={(e) => {
                e.preventDefault();
                window.open("https://themoneydnaquiz.com/privacy/", "_blank");
              }}
            >
              Privacy Policy
            </span>{" "}
            |{" "}
            <span
              style={{ cursor: "pointer" }}
              onClick={(e) => {
                e.preventDefault();
                window.open(
                  "https://themoneydnaquiz.com/terms-and-conditions/",
                  "_blank"
                );
              }}
            >
              {" "}
              Terms of Use
            </span>
          </p>
          <p>MoneyDNA LLC ©2022. All rights reserved</p>
        </div>
      </div>
    </div>
  );
}
